package com.kanzankazu.itungitungan.model

import android.os.Parcelable
import kotlinx.android.parcel.Parcelize

@Parcelize
data class Hutang(
    var hId: String = "",
    var backupBeforeChange: Hutang? = null,
    var creditorId: String = "",
    var creditorName: String = "",
    var creditorFamilyId: String = "",
    var creditorFamilyName: String = "",
    var creditorEmail: String = "",
    var creditorApprovalNew: Boolean = false,
    var creditorApprovalEdit: Boolean = false,
    var creditorApprovalDelete: Boolean = false,
    var debtorId: String = "",
    var debtorName: String = "",
    var debtorFamilyId: String = "",
    var debtorFamilyName: String = "",
    var debtorEmail: String = "",
    var debtorApprovalNew: Boolean = false,
    var debtorApprovalEdit: Boolean = false,
    var debtorApprovalDelete: Boolean = false,
    var debtorCreditorId: String = "",
    var hutangRadioIndex: Int = 0,
    var hutangKeluargaId: String = "",
    var hutangKeluargaNama: String = "",
    var hutangNominal: String = "0",
    var hutangKeperluan: String = "",
    var hutangCatatan: String = "",
    var hutangPinjam: String = "",
    var hutangProofImage: MutableList<String> = mutableListOf(),
    var hutangEditableis: Boolean = false,
    var hutangCicilanIs: Boolean = false,
    var hutangCicilanBerapaKali: String = "",
    var hutangCicilanBerapaKaliType: String = "",
    var hutangCicilanBerapaKaliPosisi: Int = 0,
    var hutangCicilanNominal: String = "0",
    var hutangCicilanIsBayarKapanSaja: Boolean = true,
    var hutangCicilanTanggalAkhir: String = "",
    var hutangPembayaranSub: MutableList<HutangPembayaran> = mutableListOf(),
    var statusLunas: Boolean = false,
    var statusDeleted: Boolean = false,
    var statusBerulang: Boolean = true,
    var createAt: String = "",
    var createBy: String = "",
    var updateAt: String = "",
    var updateBy: String = "",
    var deleteAt: String = "",
    var deleteBy: String = ""
) : Parcelable
